In [13]:
!pip install numpy

In [1]:
import numpy as np

# 1. Create

In [55]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 10)
ones = np.ones((2,2,2))

In [4]:
type(ones)

numpy.ndarray

In [4]:
data

array([[[0.29537327, 0.29653909, 0.68464021, 0.56286301],
        [0.48818211, 0.41493784, 0.82536256, 0.87268431],
        [0.91334937, 0.96686513, 0.78410488, 0.85997641]],

       [[0.21969959, 0.78896717, 0.78477582, 0.10869201],
        [0.80956658, 0.77166721, 0.37825216, 0.75815976],
        [0.29930282, 0.80387203, 0.94290859, 0.06168592]]])

In [23]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [24]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [5]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [25]:
arr = np.array([[1,2],[1,2]])

In [26]:
type(arr)

numpy.ndarray

In [27]:
arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

# 2. Read

In [5]:
# Attributes
shape = data.shape
size = data.size
types = data.dtype

In [11]:
data

array([[[0.63300418, 0.17593692, 0.13513326, 0.1916735 ],
        [0.70172506, 0.44661607, 0.57103419, 0.62720674],
        [0.50080544, 0.53911353, 0.03920947, 0.89547377]],

       [[0.96846367, 0.12312383, 0.41781795, 0.24339973],
        [0.75518958, 0.01956998, 0.35070828, 0.9485432 ],
        [0.40209481, 0.04095987, 0.50152996, 0.95999378]]])

In [20]:
# Slicing
arr = data[1][1][3]
slicer = data[0][2][0:2]
reverse = data[-1][-3][0]
singleval = data[0][0][0]

In [21]:
reverse

0.9684636728217223

In [36]:
data

array([[[0.38796997, 0.87725663, 0.87671104, 0.94073715],
        [0.81713558, 0.84183822, 0.51663735, 0.12651491],
        [0.79809775, 0.29331182, 0.29304637, 0.80345301]],

       [[0.99226407, 0.93758475, 0.0232816 , 0.66519671],
        [0.92765324, 0.08248093, 0.5821684 , 0.18031316],
        [0.39273609, 0.79520478, 0.29282367, 0.03004563]]])

In [35]:
data[0][0:2]

array([[0.38796997, 0.87725663, 0.87671104, 0.94073715],
       [0.81713558, 0.84183822, 0.51663735, 0.12651491]])

# 3. Update

In [22]:
list1 = np.random.rand(10) 
list2 = np.random.rand(10) 

In [30]:
print(list1)
print(list2)

[0.72589278 0.15510388 0.73478305 0.75786171 0.49987438 0.07326432
 0.02334401 0.27183298 0.91244486 0.05746659]
[0.32895571 0.07360814 0.18798545 0.16675329 0.41706143 0.63816911
 0.19865109 0.85018027 0.68032045 0.14867787]


In [24]:
# Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [29]:
dot    
[1 2    
3 4]

1.6349845519448063

In [33]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(data)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [34]:
log

array([[[-0.45727825, -1.73762976, -2.00149388, -1.65196187],
        [-0.35421361, -0.80605596, -0.56030619, -0.46647907],
        [-0.6915376 , -0.6178291 , -3.23883703, -0.11040235]],

       [[-0.03204431, -2.09456467, -0.87270946, -1.41305019],
        [-0.28078646, -3.93375834, -1.0478005 , -0.05282794],
        [-0.91106737, -3.19516244, -0.69009193, -0.04082848]]])

In [14]:
data

array([[[0.01038681, 0.21787218, 0.42851835, 0.64881025],
        [0.19335512, 0.21826725, 0.01899688, 0.76551894],
        [0.177093  , 0.20436728, 0.87188558, 0.22251969]],

       [[0.70927591, 0.34284349, 0.09135198, 0.4352562 ],
        [0.70341639, 0.2321961 , 0.13272667, 0.24661041],
        [0.34284819, 0.8144995 , 0.81043251, 0.66375411]]])

In [15]:
data[0][0][0] = 700

In [16]:
data

array([[[7.00000000e+02, 2.17872178e-01, 4.28518346e-01, 6.48810251e-01],
        [1.93355115e-01, 2.18267253e-01, 1.89968843e-02, 7.65518936e-01],
        [1.77092995e-01, 2.04367276e-01, 8.71885582e-01, 2.22519694e-01]],

       [[7.09275906e-01, 3.42843487e-01, 9.13519758e-02, 4.35256202e-01],
        [7.03416388e-01, 2.32196098e-01, 1.32726668e-01, 2.46610413e-01],
        [3.42848186e-01, 8.14499497e-01, 8.10432512e-01, 6.63754110e-01]]])

In [17]:
data.sort()
data

array([[[2.17872178e-01, 4.28518346e-01, 6.48810251e-01, 7.00000000e+02],
        [1.89968843e-02, 1.93355115e-01, 2.18267253e-01, 7.65518936e-01],
        [1.77092995e-01, 2.04367276e-01, 2.22519694e-01, 8.71885582e-01]],

       [[9.13519758e-02, 3.42843487e-01, 4.35256202e-01, 7.09275906e-01],
        [1.32726668e-01, 2.32196098e-01, 2.46610413e-01, 7.03416388e-01],
        [3.42848186e-01, 6.63754110e-01, 8.10432512e-01, 8.14499497e-01]]])

In [36]:
print(data.shape)

(2, 3, 4)


In [51]:
data = data.reshape((24,1))
data.shape

(24, 1)

In [56]:
data

array([[[0.30459756, 0.6436106 , 0.04490208, 0.48948811],
        [0.68950725, 0.17695198, 0.08806909, 0.47810265],
        [0.34245206, 0.35787261, 0.69868359, 0.11836746]],

       [[0.93172526, 0.63263487, 0.39823505, 0.53730206],
        [0.88589436, 0.83842115, 0.03624557, 0.18994878],
        [0.24607172, 0.56157991, 0.16763362, 0.75320552]]])

In [20]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [53]:
zeroes = np.insert(zeroes, 2, 1)
print(zeroes)

[0. 0. 1. 0. 0. 0. 0. 0. 0.]


# 4. Delete

In [54]:
data

array([[0.63300418],
       [0.17593692],
       [0.13513326],
       [0.1916735 ],
       [0.70172506],
       [0.44661607],
       [0.57103419],
       [0.62720674],
       [0.50080544],
       [0.53911353],
       [0.03920947],
       [0.89547377],
       [0.96846367],
       [0.12312383],
       [0.41781795],
       [0.24339973],
       [0.75518958],
       [0.01956998],
       [0.35070828],
       [0.9485432 ],
       [0.40209481],
       [0.04095987],
       [0.50152996],
       [0.95999378]])

In [58]:
np.delete(data, 0, axis=1)

array([[[0.68950725, 0.17695198, 0.08806909, 0.47810265],
        [0.34245206, 0.35787261, 0.69868359, 0.11836746]],

       [[0.88589436, 0.83842115, 0.03624557, 0.18994878],
        [0.24607172, 0.56157991, 0.16763362, 0.75320552]]])

In [18]:
data.shape

(2, 3, 4)

In [19]:
data

array([[[0.24796736, 0.26318018, 0.07889605, 0.64982113],
        [0.35336218, 0.56947741, 0.75375773, 0.30142644],
        [0.96675987, 0.02770207, 0.2196848 , 0.20971617]],

       [[0.5062028 , 0.87119372, 0.45062165, 0.4162111 ],
        [0.60495864, 0.95254273, 0.68392926, 0.16754938],
        [0.11248144, 0.05641981, 0.06949209, 0.61425847]]])

In [20]:
np.save("new array", data)

In [21]:
test = np.load("new array.npy")

In [22]:
test

array([[[0.24796736, 0.26318018, 0.07889605, 0.64982113],
        [0.35336218, 0.56947741, 0.75375773, 0.30142644],
        [0.96675987, 0.02770207, 0.2196848 , 0.20971617]],

       [[0.5062028 , 0.87119372, 0.45062165, 0.4162111 ],
        [0.60495864, 0.95254273, 0.68392926, 0.16754938],
        [0.11248144, 0.05641981, 0.06949209, 0.61425847]]])